name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey there :) Thanks for reporting the issue. We will get back to you as soon as we can."
        pr-message: "Thanks for contributing taking the time and contributing. Will check your pr soon! Till then.."
